let questions = [
    {
        "question": "Wer ist deutscher Rekordmeister im Volleyball der Frauen?",
        "answer_1": "MTV Stuttgart",
        "answer_2": "USC Münster",
        "answer_3": "SSC Schwerin",
        "answer_4": "Rote Raben Vilsbiburg",
        "right_answer": 3,
        "category": "sport",
        "level": 2,
    },

    {
        "question": "In welchsem Jahr war Deutschland zuletzt Handball Europameister?",
        "answer_1": "2007",
        "answer_2": "2016",
        "answer_3": "1998",
        "answer_4": "1996",
        "right_answer": 2,
        "category": "sport",
        "level": 1,
    },

    {
        "question": "Welches Land gewann die Weltmeisterschaft im Fußball nie im eigenen Land?",
        "answer_1": "Argentinien",
        "answer_2": "Frankreich",
        "answer_3": "Deutschland",
        "answer_4": "Brasilien",
        "right_answer": 4,
        "category": "sport",
        "level": 3,
    },

    {
        "question": "In welchem Jahr gewann Steffi Graf alle 4 Grand-Slam Turniere?",
        "answer_1": "1993",
        "answer_2": "1996",
        "answer_3": "Nie",
        "answer_4": "1988",
        "right_answer": 4,
        "category": "sport",
        "level": 4,
    },

    {
        "question": "Wer holte die meisten Olympische Medaillen im Reitsport?",
        "answer_1": "Deutschland",
        "answer_2": "USA",
        "answer_3": "Schweden",
        "answer_4": "Großbritiannen",
        "right_answer": 1,
        "category": "sport",
        "level": 5,
    },

    {
        "question": "Welche Position gibt es nicht im American Fottball?",
        "answer_1": "Totalback",
        "answer_2": "Quarterback",
        "answer_3": "Halfback",
        "answer_4": "Tight End",
        "right_answer": 1,
        "category": "sport",
        "level": 6,
    },

    {
        "question": "Wer ist deutscher Rekordmeister im Basketball der Herren?",
        "answer_1": "Alba Berlin",
        "answer_2": "Bayern München",
        "answer_3": "Brose Bamberg",
        "answer_4": "Bayer Leverkusen",
        "right_answer": 4,
        "category": "sport",
        "level": 7,
    },

    {
        "question": "Aus welchem Land kam der am längsten amtierende Schachweltmeister?",
        "answer_1": "Russland",
        "answer_2": "Deutschland",
        "answer_3": "Norwegen",
        "answer_4": "USA",
        "right_answer": 2,
        "category": "sport",
        "level": 8,
    },

    {
        "question": "Über den Sieg welcher Mannschaft konnte sich Bill Murray bei der World Series 2016 freuen?",
        "answer_1": "New York Yankees",
        "answer_2": "Chicago White Sox",
        "answer_3": "Chicago Cubs",
        "answer_4": "Boston Red Sox",
        "right_answer": 3,
        "category": "sport",
        "level": 9,
    },

    {
        "question": "Was ist die Höchste Geschwindkeit, die jemals in einem Formel 1 Grand Prix erreicht wurde?",
        "answer_1": "350 km/h",
        "answer_2": "361 km/h",
        "answer_3": "372 km/h",
        "answer_4": "383 km/h",
        "right_answer": 3,
        "category": "sport",
        "level": 10,
    },

    {
        "question": "Wo findet die jährliche Ironman Weltmeisterschaft statt?",
        "answer_1": "Hawaii",
        "answer_2": "New York",
        "answer_3": "Boston",
        "answer_4": "Miami",
        "right_answer": 1,
        "category": "sport",
        "level": 11,
    },

    {
        "question": "Wer gewann als erster alle 4 Springen einer Vierschanzentournee?",
        "answer_1": "Niemand",
        "answer_2": "Sven Hannawald",
        "answer_3": "Kamil Stoch",
        "answer_4": "Ryouyu Kabayashi",
        "right_answer": 2,
        "category": "sport",
        "level": 12,
    },

    {
        "question": "Wie wird ein Eishockeyspiel erntschieden, wenn in der Verlängerung kein Tor erzielt wird?",
        "answer_1": "Es werden Verlängerungen gespielt bis ein Tor fällt",
        "answer_2": "Es gibt einen Wettlauf zwischen den Kapitänen",
        "answer_3": "Es wird ausgelost",
        "answer_4": "Es wird ein Penaltyschießen ausgetragen",
        "right_answer": 4,
        "category": "sport",
        "level": 13,
    },

    {
        "question": "Wie lange wird ein Wasserballspiel gespielt?",
        "answer_1": "3 x 15 Min",
        "answer_2": "4 x 8 Min",
        "answer_3": "2 x 25 Min",
        "answer_4": "1 x 40 Min",
        "right_answer": 2,
        "category": "sport",
        "level": 14,
    },

    {
        "question": "Welche Mannschaft gewann die erste Meisterschaft der professionel Frauen Baseball Liga der USA?",
        "answer_1": "Racine Belles",
        "answer_2": "Rockford Peaches",
        "answer_3": "Kenosha Comets",
        "answer_4": "South Bend Blue Sox",
        "right_answer": 1,
        "category": "sport",
        "level": 15,
    },

    {
        "question": "In welchem Land steht dieser Fels?",
        "answer_1": "USA",
        "answer_2": "Kolumbien",
        "answer_3": "Kroatien",
        "answer_4": "Laos",
        "right_answer": 2,
        "category": "geo",
        "level": 1,
        "img": "./img/Penol.jpg",
    },
    
    {
        "question": "In welchem Land steht dieser Turm?",
        "answer_1": "Paris",
        "answer_2": "Italien",
        "answer_3": "Frankreich",
        "answer_4": "Dublin",
        "right_answer": 3,
        "category": "geo",
        "level": 2,
        "img": "./img/Eifelturm.jpg",
    },

    {
        "question": "In welchem Land finden wir dieses Bauwerk?",
        "answer_1": "Ägypten",
        "answer_2": "Sudan",
        "answer_3": "Israel",
        "answer_4": "Liberia",
        "right_answer": 1,
        "category": "geo",
        "level": 3,
        "img": "./img/Pyramide.jpg",
    },

    {
        "question": "In welchem Ort befindet sich diese Grabstelle?",
        "answer_1": "Bankok",
        "answer_2": "Istanbul",
        "answer_3": "Medina",
        "answer_4": "Agra",
        "right_answer": 4,
        "category": "geo",
        "level": 4,
        "img": "./img/Taj Mahal.jpg",
    },

    {
        "question": "Diese antiken Stätten sind ein Wahrzeichen von?",
        "answer_1": "Kambodscha",
        "answer_2": "Peru",
        "answer_3": "Mexico",
        "answer_4": "Honduras",
        "right_answer": 1,
        "category": "geo",
        "level": 5,
        "img": "./img/Ankor Thom.jpg",
    },

    {
        "question": "Welcher Fluss ist hier zu sehen?",
        "answer_1": "Rom",
        "answer_2": "Tiber",
        "answer_3": "Vatikan",
        "answer_4": "Po",
        "right_answer": 2,
        "category": "geo",
        "level": 6,
        "img": "./img/Rom.jpg",
    },

    {
        "question": "In welcher Stadt steht diese Brücker?",
        "answer_1": "Lissabon",
        "answer_2": "Mexico-City",
        "answer_3": "Quito",
        "answer_4": "San Fransico",
        "right_answer": 1,
        "category": "geo",
        "level": 7,
        "img": "./img/Lissabon.jpg",
    },
    
    {
        "question": "Zu welchem Land gehört der Affenfelsen mit Blick auf Afrika?",
        "answer_1": "Portugal",
        "answer_2": "Spanien",
        "answer_3": "Italien",
        "answer_4": "Großbritiannen",
        "right_answer": 4,
        "category": "geo",
        "level": 8,
        "img": "./img/Gibraltar.jpg",
    },

    {
        "question": "Zu welchem Land gehört die Pilgerstätte?",
        "answer_1": "Vereinigte Arabische Emirate",
        "answer_2": "Katar",
        "answer_3": "Saudi Arabien",
        "answer_4": "Bahrain",
        "right_answer": 3,
        "category": "geo",
        "level": 9,
        "img": "./img/Mekka.jpg",
    },

    {
        "question": "In welchem Land stehen die meisten dieser Pagoden?",
        "answer_1": "Thailand",
        "answer_2": "Indien",
        "answer_3": "Nepal",
        "answer_4": "Myanmar",
        "right_answer": 4,
        "category": "geo",
        "level": 10,
        "img": "./img/Pagode.jpg",
    },

    {
        "question": "In welcher Stadt steht diese Oper?",
        "answer_1": "Melbourne",
        "answer_2": "Sydney",
        "answer_3": "Perth",
        "answer_4": "Brisbane",
        "right_answer": 2,
        "category": "geo",
        "level": 11,
        "img": "./img/Opera.jpg",
    },

    {
        "question": "Dieses bunte Bauwerk ziert welche Stadt?",
        "answer_1": "St. Petersburg",
        "answer_2": "Sochi",
        "answer_3": "Moskau",
        "answer_4": "Askana",
        "right_answer": 3,
        "category": "geo",
        "level": 12,
        "img": "./img/Moscowa.jpg",
    },

    {
        "question": "Diese Seenlandschaft liegt im Nationalpark welches Landes?",
        "answer_1": "Kroatien",
        "answer_2": "Bulgarien",
        "answer_3": "Albanien",
        "answer_4": "Serbien",
        "right_answer": 1,
        "category": "geo",
        "level": 13,
        "img": "./img/Plitvicer.jpg",
    },

    {
        "question": "Die Sagrada Família ist in welchem Land zu finden?",
        "answer_1": "Kolumbien",
        "answer_2": "Peru",
        "answer_3": "Chile",
        "answer_4": "Spanien",
        "right_answer": 4,
        "category": "geo",
        "level": 14,
        "img": "./img/Sagrada de familia.jpg",
    },

    {
        "question": "In welchem Land steht diese lange Mauer?",
        "answer_1": "Portland",
        "answer_2": "China",
        "answer_3": "Brasilien",
        "answer_4": "Deutschland",
        "right_answer": 2,
        "category": "geo",
        "level": 15,
        "img": "./img/Mauer.jpg",
    },

    {
        "question": "Welche Stadt ist ein klein Paris?",
        "answer_1": "Frankfurt",
        "answer_2": "Dresden",
        "answer_3": "Leipzig",
        "answer_4": "Berlin",
        "right_answer": 3,
        "category": "literature",
        "level": 1,
    },

    {
        "question": "Wer erzählt die Ringparabel?",
        "answer_1": "Nathan der Weise",
        "answer_2": "Karl Moor",
        "answer_3": "Tybalt",
        "answer_4": "Solomon",
        "right_answer": 1,
        "category": "literature",
        "level": 2,
    },

    {
        "question": "Welches Buch sorgte 2003 für einen Aufruhr im Vatikan, weil es von einem Jesuskind erzählte?",
        "answer_1": "Habemus Papam",
        "answer_2": "Das Markus Evangelium",
        "answer_3": "Die Judas Verschwörung",
        "answer_4": "Sakrileg",
        "right_answer": 4,
        "category": "literature",
        "level": 3,
    },

    {
        "question": "Wer schrieb die Weihnachtsgeschichte in der Ebenezer Scoorge in einer Nacht Besuch von 3 Engeln bekam?",
        "answer_1": "Charles Dickens",
        "answer_2": "Mark Twain",
        "answer_3": "Astrid Lindgren",
        "answer_4": "Henry Knot",
        "right_answer": 1,
        "category": "literature",
        "level": 4,
    },

    {
        "question": "Aus welcher Feder stammt die Frage: 'Sein oder nicht sein?",
        "answer_1": "Gottholt Epraphim Lessing",
        "answer_2": "William Shakespeare",
        "answer_3": "George Händel",
        "answer_4": "Alexander Pope",
        "right_answer": 2,
        "category": "literature",
        "level": 5,
    },

    {
        "question": "Wenn verklagt Anna Fitzgerald im Film: 'Beim Leben meiner Schwester'",
        "answer_1": "Ihren Anwalt",
        "answer_2": "Die Regierung der Vereinigten Staaten",
        "answer_3": "Ihre Eltern",
        "answer_4": "Den Mann ihrer Schwester",
        "right_answer": 3,
        "category": "literature",
        "level": 6,
    },

    {
        "question": "Welches Buch von Ernest Hemingway beschreibt den Spanischen Bürgerkrieg?",
        "answer_1": "Der alte Mann und das Meer",
        "answer_2": "Paris - Ein Fest fürs Leben",
        "answer_3": "Inseln im Strom",
        "answer_4": "Wem die Stunde schlägt",
        "right_answer": 4,
        "category": "literature",
        "level": 7,
    },

    {
        "question": "Wer schrieb den Roman der den totalitäteren ÜBerwachsstaat im Jahre 1984 beschreibt?",
        "answer_1": "Aldous Huxley",
        "answer_2": "George Orwell",
        "answer_3": "Ernest Hemingway",
        "answer_4": "William Golding",
        "right_answer": 2,
        "category": "literature",
        "level": 8,
    },    

    {
        "question": "Welches Buch beginnt mit den Worten 'Nennt mich Ismael'",
        "answer_1": "Moby-Dick",
        "answer_2": "Der große Gatsby",
        "answer_3": "Die Brüder Karamasow",
        "answer_4": "Das Herz der Finsternis",
        "right_answer": 1,
        "category": "literature",
        "level": 9,
    }, 

    {
        "question": "Welcher Waisenjunge von Mark Twain lebt am Ufer des Mississipi?",
        "answer_1": "Oliver Twist",
        "answer_2": "Peter Pan",
        "answer_3": "Feivel Robinson",
        "answer_4": "Tom Saywer",
        "right_answer": 4,
        "category": "literature",
        "level": 10,
    }, 

    {
        "question": "Was möchtet der kleine Prinz gezeichnet haben",
        "answer_1": "Eine Schlange",
        "answer_2": "Ein Elefant",
        "answer_3": "Ein Schaaf",
        "answer_4": "Eine Kiste",
        "right_answer": 3,
        "category": "literature",
        "level": 11,
    }, 

    {
        "question": "In welchem Jahr wurde 'Im Westen nichts neues Veröffentlicht",
        "answer_1": "2022",
        "answer_2": "1965",
        "answer_3": "1928",
        "answer_4": "1934",
        "right_answer": 3,
        "category": "literature",
        "level": 12,
    }, 

    {
        "question": "Wer verfasste den Roman einer fiktiven Wette nach der Weltreise von George Francis Train?",
        "answer_1": "Jules Vernes",
        "answer_2": "Theodor Fontane",
        "answer_3": "Edgar Allan Poe",
        "answer_4": "Thomas Mann",
        "right_answer": 2,
        "category": "literature",
        "level": 13,
    }, 

    {
        "question": "An welchem Wettkampf nimmt Katness Everdeen teil?",
        "answer_1": "Die Quidditsch-Weltmeisterschaft",
        "answer_2": "Die Hungerspiele",
        "answer_3": "Dem Slash of Underworld",
        "answer_4": "Dem U-Bahnmarathon",
        "right_answer": 1,
        "category": "literature",
        "level": 14,
    }, 

    {
        "question": "In welcher Erzählung sitzt Richter Adam wegen seiner eigenen Tat zu Gericht.",
        "answer_1": "Die Strafkolonie",
        "answer_2": "Stolz und Vorurteil",
        "answer_3": "Der Process",
        "answer_4": "Der zerbrochene Krug",
        "right_answer": 4,
        "category": "literature",
        "level": 15,
    }, 

    {
        "question": "In welchem Jahr kam Pulp Fiction in die Kinos?",
        "answer_1": "1993",
        "answer_2": "1994",
        "answer_3": "1995",
        "answer_4": "1997",
        "right_answer": 2,
        "category": "film",
        "level": 1,
    },

    {
        "question": "Wer führte die Regie zu Blade Runner?",
        "answer_1": "Ridley Scott",
        "answer_2": "Steven Spielberg",
        "answer_3": "James Cameron",
        "answer_4": "George Lucas",
        "right_answer": 1,
        "category": "film",
        "level": 2,
    },

    {
        "question": "Für welchen Film bekam Leonardo di Caprio einen Osace als bester Hauptdarsteller?",
        "answer_1": "Titanic",
        "answer_2": "Wolf of Wallstreet",
        "answer_3": "The Revenant",
        "answer_4": "Departed",
        "right_answer": 3,
        "category": "film",
        "level": 3,
    },

    {
        "question": "Wie hieß der Freund von Forrest Gump, der einen Shrimpkutter kaufen wollte?",
        "answer_1": "Peter",
        "answer_2": "Tschiba",
        "answer_3": "Bubba",
        "answer_4": "George",
        "right_answer": 3,
        "category": "film",
        "level": 4,
    },

    {
        "question": "Wie wurde die DNA gewonnen, aus denen die Dinosaurier in Jurassic Park gezeugt wurden?",
        "answer_1": "Überresten sehr alter Quallen",
        "answer_2": "Extration aus Fossilien",
        "answer_3": "Aus einem konservierten Dinosaurier",
        "answer_4": "Aus konservierten Mücken",
        "right_answer": 4,
        "category": "film",
        "level": 5,
    },

    {
        "question": "Was ist Bilbo Beutlin?",
        "answer_1": "Ein Magier",
        "answer_2": "Ein Hobbit",
        "answer_3": "Ein Elf",
        "answer_4": "Ein Cyborg",
        "right_answer": 2,
        "category": "film",
        "level": 6,
    },

    {
        "question": "Wer spielte die Rolle von 'Neo' im Science-Fiction-Film 'The Matrix' aus dem Jahr 1999?",
        "answer_1": "Keanu Reeves",
        "answer_2": "Laurence Fishburne",
        "answer_3": "Hugo Weaving",
        "answer_4": "Carrie-Anne Moss",
        "right_answer": 1,
        "category": "film",
        "level": 7,
    },

    {
        "question": "Wer führte Regie bei dem Film 'Inception' aus dem Jahr 2010?",
        "answer_1": "Steven Spielberg",
        "answer_2": "Martin Scorsese",
        "answer_3": "Quentin Tarantino",
        "answer_4": "Christopher Nolan",
        "right_answer": 4,
        "category": "film",
        "level": 8,
    },

    {
        "question": "Was plant Danny Ocean im Film 'Ocean's' Eleven?",
        "answer_1": "Einen Roadtrip ans Meer",
        "answer_2": "Den Flug in ein Schwarzes Loch",
        "answer_3": "Einen Casinoraub",
        "answer_4": "Den perfekten Heiratsantrag",
        "right_answer": 3,
        "category": "film",
        "level": 9,
    },

    {
        "question": "Wer komponierte das berühmte Theme zu E.T.?",
        "answer_1": "Hans Zimmer",
        "answer_2": "James Horner",
        "answer_3": "John Williams",
        "answer_4": "James Newton Howard",
        "right_answer": 3,
        "category": "film",
        "level": 10,
    },

    {
        "question": "Wie heißt die FBI-Agentin, die Hilfe beim Serienmörder Hannibal Lector sucht?",
        "answer_1": "Catherine Langston",
        "answer_2": "Constance Williams",
        "answer_3": "Erin Brokovich",
        "answer_4": "Clarice Starling",
        "right_answer": 4,
        "category": "film",
        "level": 11,
    },

    {
        "question": "Wer spielt den Verhandler Chris Sabin im Film 'Verhandlungssache'?",
        "answer_1": "Samuel L. Jackson",
        "answer_2": "Kevin Spacey",
        "answer_3": "Denzel Washington",
        "answer_4": "Nicolas Cage",
        "right_answer": 2,
        "category": "film",
        "level": 12,
    },

    {
        "question": "Welche Farbe hat das einzige farbe Kleidungsstück in Schindler's Liste?",
        "answer_1": "blau",
        "answer_2": "rot",
        "answer_3": "grün",
        "answer_4": "gelb",
        "right_answer": 2,
        "category": "film",
        "level": 13,
    },

    {
        "question": "Welche Majestät trug das Herz des Ozeans bevor es in Herzform geschliffen wurde und mit Rose DeWitt Bukater die Titanic verließ?",
        "answer_1": "George III.",
        "answer_2": "Ludwig XIV.",
        "answer_3": "Harry V.",
        "answer_4": "Ludwig XVI.",
        "right_answer": 4,
        "category": "film",
        "level": 14,
    },

    {
        "question": "Warum versteckte die Haushälterin im Film Parasite ihren Mann im Keller?",
        "answer_1": "Weil er sich schlecht benommen hat.",
        "answer_2": "Weil Kredithaie hinter ihm her waren.",
        "answer_3": "Weil er schwer krank war.",
        "answer_4": "Weil er kein Sonnenlicht verturg.",
        "right_answer": 2,
        "category": "film",
        "level": 15,
    },

]